-- Thêm bài viết cho các danh mục blog

-- Xóa dữ liệu cũ
TRUNCATE TABLE bai_viet;

-- Bài viết về Chăm sóc
INSERT INTO `bai_viet` (`tieu_de`, `slug`, `tom_tat`, `noi_dung`, `hinh_anh`, `danh_muc`, `luot_xem`, `trang_thai`, `ngay_tao`) VALUES
('10 Điều Cần Biết Khi Nuôi Chó Lần Đầu', '10-dieu-can-biet-khi-nuoi-cho-lan-dau', 'Nuôi chó là một trách nhiệm lớn và đòi hỏi sự chuẩn bị kỹ lưỡng. Bạn cần tìm hiểu về giống chó phù hợp với không gian sống, thời gian chăm sóc, và khả năng tài chính của mình.', '<h2>1. Chọn giống chó phù hợp</h2><p>Mỗi giống chó có đặc điểm và nhu cầu khác nhau. Hãy nghiên cứu kỹ trước khi quyết định.</p><h2>2. Chuẩn bị không gian sống</h2><p>Đảm bảo nhà bạn đủ rộng và an toàn cho chó cưng.</p><h2>3. Trang bị đồ dùng cần thiết</h2><p>Bát ăn, nước uống, đệm ngủ, đồ chơi...</p><h2>4. Lịch tiêm phòng</h2><p>Đưa chó đi tiêm phòng đầy đủ theo lịch bác sĩ thú y.</p><h2>5. Chế độ ăn uống</h2><p>Thức ăn chất lượng phù hợp với độ tuổi và kích thước.</p>', 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800', 'cham-soc', 1250, 1, NOW()),

('Cách Chăm Sóc Lông Cho Mèo Dài Lông', 'cach-cham-soc-long-cho-meo-dai-long', 'Mèo dài lông cần được chăm sóc đặc biệt để tránh tình trạng rối lông và búi lông. Việc chải lông đều đặn không chỉ giúp lông đẹp mà còn tốt cho sức khỏe.', '<h2>Tại sao cần chăm sóc lông cho mèo?</h2><p>Lông mèo dài dễ bị rối, búi và tích tụ chất bẩn. Chải lông giúp loại bỏ lông chết, kích thích tuần hoàn máu.</p><h2>Dụng cụ cần thiết</h2><ul><li>Lược răng thưa và răng dày</li><li>Bàn chải lông mềm</li><li>Kéo cắt lông an toàn</li></ul><h2>Quy trình chải lông</h2><p>Bắt đầu từ đầu, di chuyển xuống lưng và bụng. Nhẹ nhàng với vùng nhạy cảm.</p>', 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800', 'cham-soc', 890, 1, NOW()),

('Hướng Dẫn Tắm Cho Chó An Toàn', 'huong-dan-tam-cho-cho-an-toan', 'Tắm cho chó đúng cách giúp giữ vệ sinh, ngăn ngừa bệnh da và tạo mối quan hệ thân thiết giữa bạn và thú cưng.', '<h2>Tần suất tắm phù hợp</h2><p>Chó nên tắm 2-4 tuần/lần tùy giống và hoạt động.</p><h2>Chuẩn bị</h2><ul><li>Sữa tắm chuyên dụng cho chó</li><li>Khăn tắm mềm</li><li>Máy sấy tóc (nhiệt độ thấp)</li></ul><h2>Các bước thực hiện</h2><p>1. Chải lông trước khi tắm<br>2. Điều chỉnh nhiệt độ nước phù hợp<br>3. Tránh nước vào tai và mắt<br>4. Xả sạch sữa tắm<br>5. Lau và sấy khô</p>', 'https://images.unsplash.com/photo-1616197107994-03ddd6cafdf3?w=800', 'cham-soc', 1050, 1, NOW()),

-- Bài viết về Dinh dưỡng
('Chế Độ Ăn Cân Bằng Cho Chó Trưởng Thành', 'che-do-an-can-bang-cho-cho-truong-thanh', 'Dinh dưỡng đầy đủ là nền tảng cho sức khỏe của chó. Hiểu rõ nhu cầu dinh dưỡng sẽ giúp bạn chọn thức ăn phù hợp.', '<h2>Thành phần dinh dưỡng cần thiết</h2><ul><li>Protein: 18-25% (từ thịt, cá)</li><li>Chất béo: 10-15%</li><li>Carbohydrate: 30-50%</li><li>Vitamin và khoáng chất</li></ul><h2>Lượng thức ăn mỗi ngày</h2><p>Tùy thuộc vào cân nặng, tuổi và mức độ vận động. Chia làm 2 bữa/ngày.</p><h2>Thực phẩm nên tránh</h2><p>Chocolate, nho, hành tây, xương gà, đồ ngọt...</p>', 'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800', 'dinh-duong', 1340, 1, NOW()),

('Thức Ăn Tự Nhiên vs Thức Ăn Công Nghiệp Cho Mèo', 'thuc-an-tu-nhien-vs-thuc-an-cong-nghiep-cho-meo', 'So sánh ưu nhược điểm của hai loại thức ăn để đưa ra lựa chọn phù hợp với mèo cưng của bạn.', '<h2>Thức ăn tự nhiên</h2><p><strong>Ưu điểm:</strong> Kiểm soát được nguồn gốc, tươi ngon<br><strong>Nhược điểm:</strong> Tốn thời gian, khó cân bằng dinh dưỡng</p><h2>Thức ăn công nghiệp</h2><p><strong>Ưu điểm:</strong> Tiện lợi, cân bằng dinh dưỡng, bảo quản lâu<br><strong>Nhược điểm:</strong> Có thể chứa phụ gia, giá thành cao</p><h2>Kết luận</h2><p>Có thể kết hợp cả hai loại để đảm bảo dinh dưỡng và sự đa dạng.</p>', 'https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=800', 'dinh-duong', 980, 1, NOW()),

('Top 5 Loại Rau Củ Tốt Cho Sức Khỏe Chó', 'top-5-loai-rau-cu-tot-cho-suc-khoe-cho', 'Bổ sung rau củ vào chế độ ăn giúp cung cấp chất xơ, vitamin và khoáng chất cần thiết cho chó.', '<h2>1. Cà rót</h2><p>Giàu vitamin A, tốt cho mắt và da. Nên nấu chín trước khi cho ăn.</p><h2>2. Bí đỏ</h2><p>Hỗ trợ tiêu hóa, giàu chất xơ và vitamin.</p><h2>3. Khoai lang</h2><p>Nguồn năng lượng tốt, chứa nhiều vitamin B6 và C.</p><h2>4. Bông cải xanh</h2><p>Giàu chất chống oxi hóa, nên cho ăn ít một.</p><h2>5. Đậu xanh</h2><p>Ít calo, giàu protein thực vật và vitamin.</p><p><em>Lưu ý: Luôn rửa sạch và nấu chín rau củ trước khi cho chó ăn.</em></p>', 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=800', 'dinh-duong', 760, 1, NOW()),

-- Bài viết về Huấn luyện
('Cách Dạy Chó Ngồi - Lệnh Cơ Bản Đầu Tiên', 'cach-day-cho-ngoi-lenh-co-ban-dau-tien', 'Lệnh "Ngồi" là nền tảng cho mọi bài huấn luyện khác. Đây là kỹ năng đầu tiên bạn nên dạy cho chó cưng.', '<h2>Chuẩn bị</h2><ul><li>Snack thưởng nhỏ</li><li>Không gian yên tĩnh</li><li>Thời gian kiên nhẫn</li></ul><h2>Các bước thực hiện</h2><p><strong>Bước 1:</strong> Cầm snack trước mũi chó<br><strong>Bước 2:</strong> Di chuyển tay lên cao, chó sẽ tự động ngồi<br><strong>Bước 3:</strong> Nói "Ngồi" khi chó ngồi xuống<br><strong>Bước 4:</strong> Thưởng ngay lập tức</p><h2>Lưu ý</h2><p>Luyện tập 5-10 phút/ngày, nhất quán với từ ngữ và cử chỉ.</p>', 'https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=800', 'huan-luyen', 1120, 1, NOW()),

('Huấn Luyện Mèo Sử Dụng Khay Vệ Sinh', 'huan-luyen-meo-su-dung-khay-ve-sinh', 'Mèo có bản năng chôn phân, nhưng vẫn cần được hướng dẫn sử dụng khay vệ sinh đúng cách.', '<h2>Chọn khay vệ sinh phù hợp</h2><p>Kích thước đủ lớn, có hoặc không có nắp đậy tùy sở thích mèo.</p><h2>Đặt vị trí hợp lý</h2><p>Nơi yên tĩnh, riêng tư, dễ tiếp cận, tránh gần bát ăn.</p><h2>Quy trình huấn luyện</h2><p>1. Đưa mèo vào khay sau bữa ăn<br>2. Để mèo ngửi và làm quen<br>3. Khen ngợi khi sử dụng đúng<br>4. Dọn vệ sinh khay hàng ngày</p><h2>Xử lý khi mèo đi vệ sinh sai chỗ</h2><p>Không trừng phạt, hãy đưa mèo về khay và kiểm tra nguyên nhân.</p>', 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800', 'huan-luyen', 870, 1, NOW()),

('Dạy Chó Đi Theo Không Cần Xích', 'day-cho-di-theo-khong-can-xich', 'Kỹ năng đi theo là dấu hiệu của sự vâng lời và mối quan hệ tốt giữa chó và chủ.', '<h2>Bắt đầu với xích</h2><p>Dạy chó đi bên cạnh bạn khi có xích trước, thưởng khi chó đi đúng vị trí.</p><h2>Giảm dần độ căng xích</h2><p>Để xích lỏng, chó học cách tự điều chỉnh tốc độ.</p><h2>Luyện tập không xích</h2><p>Bắt đầu ở nơi an toàn, không đông người. Dùng lệnh "Theo" và thưởng.</p><h2>Mẹo thành công</h2><ul><li>Luyện tập ngắn nhưng thường xuyên</li><li>Luôn mang theo snack</li><li>Kiên nhẫn và nhất quán</li></ul>', 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800', 'huan-luyen', 950, 1, NOW()),

-- Bài viết về Sức khỏe
('7 Dấu Hiệu Chó Bị Ốm Cần Đưa Đi Bác Sĩ', '7-dau-hieu-cho-bi-om-can-dua-di-bac-si', 'Nhận biết sớm các triệu chứng bệnh giúp điều trị kịp thời và hiệu quả hơn.', '<h2>1. Mất cảm thú ăn uống</h2><p>Không ăn hoặc giảm ăn đáng kể trong 24-48 giờ.</p><h2>2. Nôn mửa hoặc tiêu chảy</h2><p>Đặc biệt nếu kèm máu hoặc kéo dài.</p><h2>3. Khó thở hoặc ho liên tục</h2><p>Có thể là dấu hiệu của bệnh hô hấp hoặc tim mạch.</p><h2>4. Uể oải, không muốn vận động</h2><p>Thay đổi đột ngột về năng lượng.</p><h2>5. Sốt cao hoặc hạ thân nhiệt</h2><p>Nhiệt độ bình thường: 38-39°C.</p><h2>6. Thay đổi hành vi</h2><p>Hung dữ, sợ hãi hoặc ẩn nấp bất thường.</p><h2>7. Khó đi vệ sinh</h2><p>Không tiểu, tiểu ra máu hoặc đau khi đi vệ sinh.</p>', 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800', 'suc-khoe', 1560, 1, NOW()),

('Lịch Tiêm Phòng Cho Mèo Con', 'lich-tiem-phong-cho-meo-con', 'Tiêm phòng đầy đủ là cách tốt nhất để bảo vệ mèo khỏi các bệnh nguy hiểm.', '<h2>Vaccine cốt lõi (bắt buộc)</h2><p><strong>6-8 tuần tuổi:</strong> Vaccine 3 bệnh (FVRCP)<br><strong>10-12 tuần:</strong> Nhắc lại FVRCP<br><strong>14-16 tuần:</strong> Nhắc lại FVRCP + Dại</p><h2>Vaccine không cốt lõi</h2><ul><li>FeLV (Bạch cầu mèo): Nếu mèo ra ngoài</li><li>FIV: Theo khuyến nghị bác sĩ</li></ul><h2>Nhắc lại hàng năm</h2><p>Vaccine dại và 3 bệnh cần được nhắc lại theo lịch.</p><h2>Lưu ý</h2><p>Mèo cần khỏe mạnh khi tiêm, tránh tắm 3 ngày sau tiêm.</p>', 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=800', 'suc-khoe', 1180, 1, NOW()),

('Cách Chăm Sóc Răng Miệng Cho Chó', 'cach-cham-soc-rang-mieng-cho-cho', 'Vệ sinh răng miệng giúp phòng ngừa bệnh nướu răng và các vấn đề sức khỏe nghiêm trọng.', '<h2>Tại sao cần chăm sóc răng?</h2><p>Cao răng và viêm nướu có thể dẫn đến nhiễm trùng, mất răng và ảnh hưởng tim gan thận.</p><h2>Cách đánh răng cho chó</h2><p>1. Dùng bàn chải và kem đánh răng chuyên dụng<br>2. Bắt đầu từ từ, cho chó làm quen<br>3. Đánh 2-3 lần/tuần<br>4. Tập trung vào răng hàm và nanh</p><h2>Phương pháp khác</h2><ul><li>Xương gặm sạch răng</li><li>Nước súc miệng cho chó</li><li>Thức ăn khô giúp làm sạch răng</li></ul><h2>Khi nào cần đến bác sĩ?</h2><p>Hôi miệng nghiêm trọng, nướu sưng đỏ, chảy máu, răng lung lay.</p>', 'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=800', 'suc-khoe', 890, 1, NOW()),

-- Bài viết về Hành vi
('Hiểu Ngôn Ngữ Cơ Thể Của Chó', 'hieu-ngon-ngu-co-the-cua-cho', 'Chó giao tiếp chủ yếu qua ngôn ngữ cơ thể. Hiểu được điều này giúp bạn kết nối tốt hơn với chó cưng.', '<h2>Đuôi</h2><p><strong>Vẫy mạnh:</strong> Vui vẻ, hào hứng<br><strong>Đuôi thấp:</strong> Lo lắng, sợ hãi<br><strong>Đuôi cứng:</strong> Cảnh giác, sẵn sàng tấn công</p><h2>Tai</h2><p><strong>Dựng lên:</strong> Chú ý, tò mò<br><strong>Cụp xuống:</strong> Sợ hãi, phục t种</p><h2>Mắt</h2><p><strong>Nhìn thẳng:</strong> Thách thức<br><strong>Tránh ánh mắt:</strong> Phục tùng</p><h2>Tư thế</h2><p><strong>Cúi đầu, nâng mông:</strong> Muốn chơi<br><strong>Co ro:</strong> Sợ hãi<br><strong>Đứng thẳng:</strong> Tự tin, khẳng định</p>', 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800', 'hanh-vi', 1030, 1, NOW()),

('Tại Sao Mèo Hay Cào Đồ Đạc?', 'tai-sao-meo-hay-cao-do-dac', 'Cào là hành vi tự nhiên của mèo, không phải để phá hoại mà để đánh dấu lãnh thổ và mài móng.', '<h2>Lý do mèo cào</h2><ul><li>Mài móng, loại bỏ lớp móng già</li><li>Đánh dấu lãnh thổ (tuyến mùi ở bàn chân)</li><li>Duỗi cơ bắp</li><li>Giảm stress</li></ul><h2>Cách ngăn chặn</h2><p>1. Cung cấp cột cào chất lượng<br>2. Đặt ở vị trí mèo hay cào<br>3. Dùng catnip để thu hút<br>4. Khen ngợi khi cào đúng chỗ</p><h2>Bảo vệ đồ đạc</h2><p>Dùng băng dính 2 mặt, xịt mùi chanh, hoặc che phủ tạm thời.</p>', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800', 'hanh-vi', 920, 1, NOW()),

('Xử Lý Chó Sủa Quá Nhiều', 'xu-ly-cho-sua-qua-nhieu', 'Sủa là cách chó giao tiếp, nhưng sủa quá nhiều có thể là vấn đề cần giải quyết.', '<h2>Nguyên nhân chó sủa</h2><ul><li>Cảnh báo, bảo vệ lãnh thổ</li><li>Sợ hãi, lo âu</li><li>Thiếu vận động, năng lượng dư thừa</li><li>Muốn được chú ý</li><li>Đau đớn, khó chịu</li></ul><h2>Giải pháp</h2><p><strong>Tăng vận động:</strong> Dắt đi dạo, chơi đùa nhiều hơn<br><strong>Huấn luyện lệnh "Im lặng":</strong> Thưởng khi chó ngừng sủa<br><strong>Loại bỏ kích thích:</strong> Che cửa sổ, tạo môi trường yên tĩnh<br><strong>Không la mắng:</strong> Càng la chó càng sủa nhiều</p><h2>Khi nào cần chuyên gia?</h2><p>Nếu sủa do lo âu phân ly hoặc hành vi cưỡng chế.</p>', 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800', 'hanh-vi', 1100, 1, NOW());
