SET NAMES utf8mb4;
SET CHARACTER_SET_CLIENT = utf8mb4;
SET CHARACTER_SET_RESULTS = utf8mb4;
SET CHARACTER_SET_CONNECTION = utf8mb4;

INSERT INTO bai_viet (tieu_de, slug, tom_tat, noi_dung, hinh_anh, danh_muc, luot_xem, trang_thai, ngay_tao) VALUES
('10 Điều Cần Biết Khi Nuôi Chó Lần Đầu', '10-dieu-can-biet-khi-nuoi-cho-lan-dau', 'Nuôi chó là một trách nhiệm lớn và đòi hỏi sự chuẩn bị kỹ lưỡng. Bạn cần tìm hiểu về giống chó phù hợp với không gian sống, thời gian chăm sóc, và khả năng tài chính của mình.', '<h2>1. Chọn giống chó phù hợp</h2><p>Mỗi giống chó có đặc điểm và nhu cầu khác nhau. Hãy nghiên cứu kỹ trước khi quyết định.</p><h2>2. Chuẩn bị không gian sống</h2><p>Đảm bảo nhà bạn đủ rộng và an toàn cho chó cưng.</p>', 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800', 'cham-soc', 1250, 1, NOW()),
('Cách Chăm Sóc Lông Cho Mèo Dài Lông', 'cach-cham-soc-long-cho-meo-dai-long', 'Mèo dài lông cần được chăm sóc đặc biệt để tránh tình trạng rối lông và búi lông. Việc chải lông đều đặn không chỉ giúp lông đẹp mà còn tốt cho sức khỏe.', '<h2>Tại sao cần chăm sóc lông cho mèo?</h2><p>Lông mèo dài dễ bị rối, búi và tích tụ chất bẩn. Chải lông giúp loại bỏ lông chết, kích thích tuần hoàn máu.</p>', 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800', 'cham-soc', 890, 1, NOW()),
('Hướng Dẫn Tắm Cho Chó An Toàn', 'huong-dan-tam-cho-cho-an-toan', 'Tắm cho chó đúng cách giúp giữ vệ sinh, ngăn ngừa bệnh da và tạo mối quan hệ thân thiết giữa bạn và thú cưng.', '<h2>Tần suất tắm phù hợp</h2><p>Chó nên tắm 2-4 tuần/lần tùy giống và hoạt động.</p>', 'https://images.unsplash.com/photo-1616197107994-03ddd6cafdf3?w=800', 'cham-soc', 1050, 1, NOW()),
('Chế Độ Ăn Cân Bằng Cho Chó Trưởng Thành', 'che-do-an-can-bang-cho-cho-truong-thanh', 'Dinh dưỡng đầy đủ là nền tảng cho sức khỏe của chó. Hiểu rõ nhu cầu dinh dưỡng sẽ giúp bạn chọn thức ăn phù hợp.', '<h2>Thành phần dinh dưỡng cần thiết</h2><p>Protein: 18-25% (từ thịt, cá), Chất béo: 10-15%</p>', 'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800', 'dinh-duong', 1340, 1, NOW()),
('Thức Ăn Tự Nhiên vs Công Nghiệp Cho Mèo', 'thuc-an-tu-nhien-vs-cong-nghiep-cho-meo', 'So sánh ưu nhược điểm của hai loại thức ăn để đưa ra lựa chọn phù hợp với mèo cưng của bạn.', '<h2>Thức ăn tự nhiên</h2><p>Ưu điểm: Kiểm soát được nguồn gốc, tươi ngon</p>', 'https://images.unsplash.com/photo-1548802673-380ab8ebc7b7?w=800', 'dinh-duong', 980, 1, NOW()),
('Top 5 Loại Rau Củ Tốt Cho Chó', 'top-5-loai-rau-cu-tot-cho-cho', 'Bổ sung rau củ vào chế độ ăn giúp cung cấp chất xơ, vitamin và khoáng chất cần thiết cho chó.', '<h2>1. Cà rốt</h2><p>Giàu vitamin A, tốt cho mắt và da.</p>', 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=800', 'dinh-duong', 760, 1, NOW()),
('Cách Dạy Chó Ngồi - Lệnh Cơ Bản', 'cach-day-cho-ngoi-lenh-co-ban', 'Lệnh Ngồi là nền tảng cho mọi bài huấn luyện khác. Đây là kỹ năng đầu tiên bạn nên dạy cho chó cưng.', '<h2>Chuẩn bị</h2><p>Snack thưởng nhỏ, không gian yên tĩnh, thời gian kiên nhẫn</p>', 'https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=800', 'huan-luyen', 1120, 1, NOW()),
('Huấn Luyện Mèo Dùng Khay Vệ Sinh', 'huan-luyen-meo-dung-khay-ve-sinh', 'Mèo có bản năng chôn phân, nhưng vẫn cần được hướng dẫn sử dụng khay vệ sinh đúng cách.', '<h2>Chọn khay vệ sinh phù hợp</h2><p>Kích thước đủ lớn, có hoặc không có nắp đậy.</p>', 'https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800', 'huan-luyen', 870, 1, NOW()),
('Dạy Chó Đi Theo Không Cần Xích', 'day-cho-di-theo-khong-can-xich', 'Kỹ năng đi theo là dấu hiệu của sự vâng lời và mối quan hệ tốt giữa chó và chủ.', '<h2>Bắt đầu với xích</h2><p>Dạy chó đi bên cạnh bạn khi có xích trước.</p>', 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800', 'huan-luyen', 950, 1, NOW()),
('7 Dấu Hiệu Chó Bị Ốm', '7-dau-hieu-cho-bi-om', 'Nhận biết sớm các triệu chứng bệnh giúp điều trị kịp thời và hiệu quả hơn.', '<h2>1. Mất cảm thú ăn uống</h2><p>Không ăn hoặc giảm ăn đáng kể trong 24-48 giờ.</p>', 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800', 'suc-khoe', 1560, 1, NOW()),
('Lịch Tiêm Phòng Cho Mèo Con', 'lich-tiem-phong-cho-meo-con', 'Tiêm phòng đầy đủ là cách tốt nhất để bảo vệ mèo khỏi các bệnh nguy hiểm.', '<h2>Vaccine cốt lõi</h2><p>6-8 tuần tuổi: Vaccine 3 bệnh (FVRCP)</p>', 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=800', 'suc-khoe', 1180, 1, NOW()),
('Chăm Sóc Răng Miệng Cho Chó', 'cham-soc-rang-mieng-cho-cho', 'Vệ sinh răng miệng giúp phòng ngừa bệnh nướu răng và các vấn đề sức khỏe nghiêm trọng.', '<h2>Tại sao cần chăm sóc răng?</h2><p>Cao răng và viêm nướu có thể gây nhiễm trùng.</p>', 'https://images.unsplash.com/photo-1477884213360-7e9d7dcc1e48?w=800', 'suc-khoe', 890, 1, NOW()),
('Hiểu Ngôn Ngữ Cơ Thể Của Chó', 'hieu-ngon-ngu-co-the-cua-cho', 'Chó giao tiếp chủ yếu qua ngôn ngữ cơ thể. Hiểu được điều này giúp bạn kết nối tốt hơn.', '<h2>Đuôi</h2><p>Vẫy mạnh: Vui vẻ, hào hứng. Đuôi thấp: Lo lắng, sợ hãi.</p>', 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800', 'hanh-vi', 1030, 1, NOW()),
('Tại Sao Mèo Hay Cào Đồ Đạc?', 'tai-sao-meo-hay-cao-do-dac', 'Cào là hành vi tự nhiên của mèo, không phải để phá hoại mà để đánh dấu lãnh thổ và mài móng.', '<h2>Lý do mèo cào</h2><p>Mài móng, đánh dấu lãnh thổ, duỗi cơ bắp, giảm stress.</p>', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800', 'hanh-vi', 920, 1, NOW()),
('Xử Lý Chó Sủa Quá Nhiều', 'xu-ly-cho-sua-qua-nhieu', 'Sủa là cách chó giao tiếp, nhưng sủa quá nhiều có thể là vấn đề cần giải quyết.', '<h2>Nguyên nhân chó sủa</h2><p>Cảnh báo, bảo vệ lãnh thổ, sợ hãi, thiếu vận động.</p>', 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800', 'hanh-vi', 1100, 1, NOW());